### ISSUE TITLE
Whether to support require import and use

### ISSUE THREAD

**Issue by wanglike** [udarrr/TemplateMatcher#17]
Hello, I found that the official @ nut-tree/template-matcher library of nutjs has stopped maintenance and does not support the mac system. I occasionally see this library of yours. I have a few questions. Do you support require import and use, and which platforms are supported?

**Comment by udarrr** [comment]
> Hello, I found that the official @ nut-tree/template-matcher library of nutjs has stopped maintenance and does not support the mac system. I occasionally see this library of yours. I have a few questions. Do you support require import and use, and which platforms are supported?

Hi @wanglike orginal lib being replaced in v.4.6.2 to '@nut-tree-fork/nut-js' for the time being. Afterward in major version i'll exclude @nut-tree at all and left only standalone mode

**Comment by udarrr** [comment]
resolved in 4.6.2
